name: hue
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  hive_flutter: ^1.1.0
  iconsax: ^0.0.8 
  cupertino_icons: ^1.0.8
  flutter_rating_bar: ^4.0.0
  shimmer: ^2.0.0
  video_player: ^2.9.2
  image_picker: ^1.0.4
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  #====== DataBase ======
  supabase_flutter: ^2.8.4
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Video/
    - assets/images/
  
flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/
  filename: assets.dart
  field_prefix: ''
